### ISSUE TITLE
Docker-Compose not working

### ISSUE THREAD

**Issue by Panda260** [p-hueber/prefetcharr#11]
Hey, the docker compose file isn't working because it can't pull the image
![image](https://github.com/p-hueber/prefetcharr/assets/52088459/d0cd1923-47c4-41cc-91e6-e2e38f022189)
![image](https://github.com/p-hueber/prefetcharr/assets/52088459/4db5ded1-ed33-4bc6-b559-f266a5c06f03)

**Comment by p-hueber** [comment]
@Panda260 there is no image to pull, it needs to be built from source. The error message already tells you to run `docker compose build` to do that. I don't know whether the tool you are using is capable of doing that.
