### ISSUE TITLE
Supply prebuilt docker image

### ISSUE THREAD

**Issue by schumi4** [p-hueber/prefetcharr#30]
Hi,

while building works fine, it is kind of bothersome and doesn't allow a compose-file with other services to just be pulled.
I'm not familiar with specifics and how much work the setup is, but I would greatly appreciate you supplying a prebuilt image via Docker Hub or GHCR.

Thanks for considering!

**Comment by PCJones** [comment]
Just FYI it's pretty simple to do this, here is how I do it:
https://github.com/PCJones/UmlautAdaptarr/blob/master/build_and_push_docker_image.bat

It can also be automated of course

**Comment by p-hueber** [comment]
@PCJones thanks!
I plan to add a github action for it soonish

**Comment by p-hueber** [comment]
you may pull `phueber/prefetcharr:latest` from docker hub now.
It's based off the current `main` and will follow releases from here on.
