### ISSUE TITLE
Prefetcharr for multiple Sonarr Instance

### ISSUE THREAD

**Issue by DerChris119** [p-hueber/prefetcharr#56]
Dear lovely People,

i just found your extremly nice Project and wanted to use it. It is just such a nice Idea. Sadly i run multiple Instance of Sonarr and cant get it to work like that. Here is a thing i tried:

```
      # Sonarr baseurl
      - SONARR_URL=http://192.168.10.6:8989
      # Sonarr API key
      - SONARR_API_KEY=xxxxxxx
      # Sonarr4k baseurl
      - SONARR4K_URL=http://192.168.10.7:8989
      # Sonarr4k API key
      - SONARR4K_API_KEY=xxxxxxxxx
      # SonarrRemux baseurl
      - SONARRREMUX_URL=http://192.168.10.11:8989
      # SonarrRemux API key
      - SONARRREMUX_API_KEY=xxxxxx
```

Here is the Error i get like that:

```
2024-10-30T10:11:45.199606Z ERROR prefetcharr: Probing Sonarr failed: error sending request for url (http://192.168.10.6/api): client error (Connect): tcp connect error: Operation timed out (os error 110): Operation timed out (os error 110)

2024-10-30T10:11:45.199666Z  INFO prefetcharr: prefetcharr exits due to an error

Error: Probing Sonarr failed

Caused by:

    0: error sending request for url (http://192.168.10.6/api)

    1: client error (Connect)

    2: tcp connect error: Operation timed out (os error 110)

    3: Operation timed out (os error 110)
```
I have tried it without the Ports too. 

Maybe you know a Soultion?

And i am Sorry if i use this Wrong. I am new to Github and i searched for something like Comments but only found Issues.

Greetings Chris

**Comment by p-hueber** [comment]
Hi Chris,
asking for help here is fine, as long as it's about `prefetcharr`.
There is no support for connecting to multiple sonarr instances. E.g. the `SONARR4K_URL` variable you made up will be ignored altogether. But there is nothing keeping you from running multiple instances of `prefetcharr` instead to support your setup.
I can't say much about your connectivity issues unfortunately. Maybe reading up in docker network helps. The timeout suggests that packets to or from that IP are filtered somewhere.

**Comment by DerChris119** [comment]
Hi p-hueber,

thank you very much for your answer :D The Idea of multiple prefetcharr sounds nice. I will give it a try. With the Networking i am still struggeling, but i hope ill find it out :)

Have a nice Day
