### ISSUE TITLE
Actually check if the season is missing and just not unmonitored

### ISSUE THREAD

**Issue by PCJones** [p-hueber/prefetcharr#9]
I currently have some shows/seasons where I already have imported the season, but the season itself is unmonitored so that Sonarr won't upgrade it.

It seems like this tool only checks for weather or not the next season is monitored - so in this case, it will start monitoring season 2 even though it is already downloaded:
![grafik](https://github.com/p-hueber/prefetcharr/assets/377223/5a944826-bf80-4715-aa58-99d2270c2f78)

A possible quick workaround would be to check if the current season is unmonitored, and if it is then the next one won't be set to monitored. Could be an optional setting of course.

**Comment by p-hueber** [comment]
Hi @PCJones, thanks for your feedback! This behavior [changed in 0.2.0](https://github.com/p-hueber/prefetcharr/blob/main/CHANGELOG.md#changed-1) already.
I'd recommend to rebuild from `latest` tag.

**Comment by PCJones** [comment]
Whoops, sorry, I totally missed that. Thanks, great work!
